### ISSUE TITLE
Documentation Bootstrap Typo

### ISSUE THREAD

**Issue by ZachGray** [nxt-dev/nxt_editor#104]
main_window shown twice in dev setup

`instance = nxt_editor.main_window.MainWindow(filepath=LAUNCH_FILE)`

https://nxt-dev.github.io/install/#developer-installation

**Comment by ImLucasBrown** [comment]
Fixed
https://github.com/nxt-dev/nxt-dev.github.io/commit/a62fd22f2262209e0709736630ebed18caecf01e
