### ISSUE TITLE
Code disappearing until re-comp

### ISSUE THREAD

**Issue by matthew-schiller** [nxt-dev/nxt_editor#138]
When editing some nodes not on the top layer the code disappears when the changes are committed and don't show up again until a full re-comp. Please see the open rig biped graph for examples.

**Comment by matthew-schiller** [comment]
https://user-images.githubusercontent.com/29157628/105092955-d6101e80-5a56-11eb-827a-e62aebd260cc.mp4

**Comment by ImLucasBrown** [comment]
Not an issue with the editor code, moved to core: https://github.com/nxt-dev/nxt/issues/52
