### ISSUE TITLE
Maya NXT Plugin force Maya to hang.

### ISSUE THREAD

**Issue by wolzjohannes** [nxt-dev/nxt_editor#147]
https://user-images.githubusercontent.com/45787327/105330335-750d5580-5bd2-11eb-8d3a-03f5c953c688.mp4

Maya nxt plugin force maya to hang! When i start the nxt editor in maya it let maya hang when i try to create a node in maya. It doesnt matter if i create the node via nxt or in maya.

My screencast will show how to reproduce the problem!

**Desktop (please complete the following information):**
 - OS: Linux Centos 7, Gnome Desktop Version 3.28.2, Huawai Matebook 13 Zoll
 - DCC: Maya 2018 Student Version
 - Version: Maya PlugIn Editor v3.5.1 / Graph v.1.17 / API v0.9.1 / Python 2.7.11

**Comment by ImLucasBrown** [comment]
Hi Wolz.
I've tried to reproduce the bug you're experiencing, but I can't seem to get it to happen.
Can you make another screen recording, this time with the Maya log visible at all times?
I'm trying to understand the error Maya spits out every time you select something in that video. I believe it may be related to a callback we have setup and that error in the log should point me in the direction of the bug.

**Comment by wolzjohannes** [comment]
Hey Dude,yeah i will do! But here is the error maya throw if i select
something!

// Error: <function selCom at 0x7f29c5c04aa0>; //

// Error: Line 1.1: Syntax error //

Thx a lot 
Am Freitag, den 22.01.2021, 08:14 -0800 schrieb ImLucasBrown:

**Comment by ImLucasBrown** [comment]
Hmm, I don't think that error is related.
Does Maya ever become responsive or does it stay frozen forever?
We've never had an issue with NXT Maya on Centos before, I'm very intrigued as to what's causing this.

**Comment by wolzjohannes** [comment]
Hey guys! I found the issue! I had this env variable in my Maya.env file!
MAYA_COLOR_MGT_NO_LOGGING=1
When delete it works fine!
