### ISSUE TITLE
Attributes with (*) text failing

### ISSUE THREAD

**Issue by matthew-schiller** [nxt-dev/nxt_editor#171]
**Describe the bug**
Any variation of open and close parenthesis with an asterisk character somewhere in between those parentheses in an attribute's text is evaluating on code execute for the node.

**To Reproduce**
-Create node
-Add attribute with (*) text
-Execute the node

**Comment by ImLucasBrown** [comment]
Moved to: https://github.com/nxt-dev/nxt/issues/76
