### ISSUE TITLE
Fatal Error - Zooming out of Graph

### ISSUE THREAD

**Issue by jicdesigns** [nxt-dev/nxt_editor#177]
In an unsaved layer, zooming out in the graph will cycle a lot of error windows, then ultimately crash Maya.  I'm unable to save out crash log with all the created windows.

**To Reproduce**

1.  New NXT Editor scene
2. Create new node
3. Zoom or pan out of graph
4. Fatal Error/ Crash NXT Editor and Maya

**Expected behavior**
It would be great to not have it crash everything.  😄 

**Desktop**
 - OS: Windows 10
 - Maya
 - Version 3.8.0

![Screenshot 2021-03-13 045250](https://user-images.githubusercontent.com/80572942/111026410-11c0c800-83b8-11eb-9998-ca887e682db1.jpg)

**Comment by jicdesigns** [comment]
It happens with saved graphs too.

**Comment by ImLucasBrown** [comment]
Good catch, fixed in [Editor v3.8.1](https://github.com/nxt-dev/nxt_editor/releases/tag/editor_v3.8.1)

**Comment by jicdesigns** [comment]
Fantastic!  Thanks, Lucas!
