### ISSUE TITLE
maya installation error

### ISSUE THREAD

**Issue by macross27** [nxt-dev/nxt_editor#216]
**Describe the bug**
After I drag "drag_into_maya.py" onto Maya app and restarted Maya, when I activate the nxt plugin, these are the errors that I got.
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: ImportError: file X:/temp/nxt/nxt_editor-editor_v3.10.0/nxt_editor/integration/maya/plug-ins/nxt_maya.py line 17: No module named Qt // 
# sys:1: Warning: Failed to run file: X:/temp/nxt/nxt_editor-editor_v3.10.0/nxt_editor/integration/maya/plug-ins/nxt_maya.py
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: ImportError: file X:/temp/nxt/nxt_editor-editor_v3.10.0/nxt_editor/integration/maya/plug-ins/nxt_maya.py line 17: No module named Qt // 
// Warning: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Failed to run file: X:/temp/nxt/nxt_editor-editor_v3.10.0/nxt_editor/integration/maya/plug-ins/nxt_maya.py // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317:  (nxt_maya) // 

It seems that Maya wasn't able to find dependencies of nxt-editor library. Thanks! 

**To Reproduce**
1. Open Maya
2. Drag drag_into_maya.py
3. restart maya
4. activate nxt plugin

**Expected behavior**
It won't install as demonstrated on youtube. Maybe there must be some path settings that I have to set to match yours.

**Screenshots**
![image](https://user-images.githubusercontent.com/67554225/139851129-84442d39-64f0-463d-8b84-5660af4ffd78.png)

**Desktop (please complete the following information):**
windows 10
maya2020

**Additional context**
Add any other context about the problem here. Attach traceback here if possible.

**Comment by ImLucasBrown** [comment]
Please make sure you're downloading the `nxt_maya.zip` from our [latest release](https://github.com/nxt-dev/nxt_editor/releases/latest), _not_ the source code zip.

**Comment by macross27** [comment]
I just downloaded from your latest release and ran the steps. Same errors occurred.
myTempEDPF.executeDroppedPythonFile("C:/Program Files/Autodesk/nxt/drag_into_maya.py", "")
del myTempEDPF
Placed nxt mod file at D:/MayaProject/modules\nxt.mod
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: ImportError: file F:/Downloads/nxt_editor-editor_v3.10.0/nxt_editor/integration/maya/plug-ins/nxt_maya.py line 17: No module named Qt // 
# sys:1: Warning: Failed to run file: F:/Downloads/nxt_editor-editor_v3.10.0/nxt_editor/integration/maya/plug-ins/nxt_maya.py
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: ImportError: file F:/Downloads/nxt_editor-editor_v3.10.0/nxt_editor/integration/maya/plug-ins/nxt_maya.py line 17: No module named Qt // 
// Warning: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Failed to run file: F:/Downloads/nxt_editor-editor_v3.10.0/nxt_editor/integration/maya/plug-ins/nxt_maya.py // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317:  (nxt_maya) //

**Comment by macross27** [comment]
btw, I was able to open nxt editor by adding "sys.path.append" line in the plugin file. I know this isn't a proper way of installing your plugin.

![image](https://user-images.githubusercontent.com/67554225/140022530-57c9584c-3ade-4396-bced-13271f294348.png)

**Comment by macross27** [comment]
I tested on maya2022 and it works fine. Maybe there was a problem with my maya 2020 configurations. Thanks!
