### ISSUE TITLE
please supprot __future__ import

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [nxt-dev/nxt_editor#218]
**Is your feature request related to a problem? Please describe.**
Python2 should add three line of `__future__` module to compat some feature from python3

```python
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import
```

but right now add code into the nxt node will pop up error below.
`SyntaxError: from __future__ imports must occur at the beginning of the file`

![image](https://user-images.githubusercontent.com/40897360/141034041-1457f3e1-9bc7-4fbd-b7a3-81e6f1ff91b6.png)

**Comment by ImLucasBrown** [comment]
Simple mistake on my part. Will be fixed in the next release.

**Comment by MichaelAldrich** [comment]
Was fixed here, https://github.com/nxt-dev/nxt/releases/tag/api_v0.13.0

Sorry for the late notice
