### ISSUE TITLE
Other integrations?

### ISSUE THREAD

**Issue by melMass** [nxt-dev/nxt_editor#225]
Hi,

I can see in a few places that you have beta Houdini and Nuke integrations, are these accessible somehow? 😅 

(Amazing project btw 😍 )

**Comment by melMass** [comment]
Or is there an integration guide somewhere?

**Comment by ImLucasBrown** [comment]
If you scroll to the bottom of [this page](https://nxt-dev.github.io/install/#developer-installation) it has some rough code for bootstrapping NXT into other DCCs. Aspirationally , we'd like to have a drag and drop solution for Houdini and Nuke.

**Comment by melMass** [comment]
> If you scroll to the bottom of [this page](https://nxt-dev.github.io/install/#developer-installation) it has some rough code for bootstrapping NXT into other DCCs. Aspirationally , we'd like to have a drag and drop solution for Houdini and Nuke.

Perfect! I missed it somehow, I'm going to give it a go.
