### ISSUE TITLE
Python 3.7+ support?

### ISSUE THREAD

**Issue by melMass** [nxt-dev/nxt_editor#226]
**Is your feature request related to a problem? Please describe.**
I've tried to build `nxt-core` and `nxt-editor` with Python 3.9.7 (blender 3.0 release) but it obviously failed 

**Describe the solution you'd like**
Can you explain what the issue is with 3.7+? Are there plans to support it?

Thanks

**Comment by ImLucasBrown** [comment]
Python 3.9 is coming, hopefully before the end of the year to keep in line with the VFX reference platform. 
In my testing it seems to _just_ work, but I haven't fully tested the core and editor in 3.9.7. 
If your really keen to get NXT working in 3.9 you could edit the source of the `setup.py`, it might _just_ work for you. I haven't looked at Blender 3 yet, we might need to do more for that to work.

**Comment by melMass** [comment]
> if your really keen to get NXT working in 3.9 you could edit the source of the `setup.py`, it might _just_ work for you. I haven't looked at Blender 3 yet, we might need to do more for that to work.

Thanks, that's what I did but it failed for a few reasons (also replacing `is` and `is not` instances by `==` and `!=`)
Something related to Shiboken, I can post the full output tomorrow if it can help. What I was wondering is what is the main reason 3.7+ are not supported yet, that might help finding the solution, thanks

**Comment by ImLucasBrown** [comment]
A PR is up for Blender 3.0 support, a release will come shortly after that is approved and merged.
I found to fix the `shiboken2` import errors (in Blender 2.81) I had to install Python 3.7.4 on my machine. After that Blender started to behave. Feels like that is a Blender bug. 🤔
