### ISSUE TITLE
AttributeError on executing nxt.exe without any arguments 

### ISSUE THREAD

**Issue by satishgoda** [nxt-dev/nxt_editor#235]
**Describe the bug**
Running nxt.exe from the command line (without any arguments) results in a traceback.

**To Reproduce**
1. Go to terminal
2. Run nxt.exe
3. See error

**Expected behavior**
I was expecting the help text to be printed.
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Centos 7, OSX]
 - Version [Graph v1.7, API v0.13.1]

**Additional context**
```
(nxtenv) PS C:\pipeline\pyenv> nxt.exe
Traceback (most recent call last):
  File "C:\pipeline\pyenv\nxtenv\Scripts\nxt-script.py", line 33, in <module>
    sys.exit(load_entry_point('nxt-core==0.13.1', 'console_scripts', 'nxt')())
  File "C:\pipeline\pyenv\nxtenv\lib\site-packages\nxt\cli.py", line 245, in main
    if args.which == 'legacy':
AttributeError: 'Namespace' object has no attribute 'which'
```

**Comment by MichaelAldrich** [comment]
Fixed by https://github.com/nxt-dev/nxt/pull/100
