### ISSUE TITLE
Deactivate multiple nodes at once Comps multiple times

### ISSUE THREAD

**Issue by wyoder** [nxt-dev/nxt_editor#248]
**Describe the bug**
If you have a large graph and deactivate multiple nodes at once, it seems to deactivate one at a time and comp every time it does one.

**To Reproduce**
1. Select multiple nodes to deactivate
2. Hit D to deactivate the nodes
3. Watch as it comps and updates one at a time.

**Expected behavior**
It runs deactivate on all nodes first before running the comp again.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DCC: Maya
 - Version: (nxt maya  - graph v1.17, api v0.14.0, editor v3.12.0)
 
![dactivate_multiple_comps](https://user-images.githubusercontent.com/4167012/177199786-d10b95e1-76cb-4e3d-947b-6234eb0825f4.gif)

**Comment by ImLucasBrown** [comment]
Fix coming in next release.
