### ISSUE TITLE
New releases not getting picked up on PyPi

### ISSUE THREAD

**Issue by gbowlds-spire** [nxt-dev/nxt_editor#259]
Hey, I was sent a request from our riggers to update our current version of nxt, but it looks like I can't grab 3.13.2, only 3.13.0 is available on through pip.

**Comment by ImLucasBrown** [comment]
Sorry about that, looks like our CI didn't run for some reason. The core and editor have both been pushed to PyPi now.
https://pypi.org/project/nxt-core/0.15.2/
https://pypi.org/project/nxt-editor/3.13.2/

**Comment by ImLucasBrown** [comment]
Turns out the bug I tried to fix in `3.13.2` was still there in some cases. Another patch release has gone out:
https://pypi.org/project/nxt-core/0.15.3/ 
https://pypi.org/project/nxt-editor/3.13.3/
